#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
if (process.argv.slice(2).some((arg) => arg !== '--check')) {
  throw new Error('Usage: node scripts/build-roles.mjs [--check]');
}
const body = (text) => text.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, '').trim();
const receiving = body(await readFile(path.join(root, 'skills/dispatched/SKILL.md'), 'utf8'));
const definitions = [
  ['taskforce_owner', 'Continuing owner of a bounded outcome through investigation, authorized implementation and local verification.', 'workstream-owner.md'],
  ['taskforce_verifier', 'Independent verifier of artifacts and acceptance evidence in a fresh context.', 'independent-verifier.md'],
  ['taskforce_helper', 'Focused map, check or settled subtask; return evidence without taking over the wider outcome.', null],
];
const banner = '# Generated by rubato-codex/scripts/build-roles.mjs. Edit bundled skill sources instead.';
const runtime = `# Codex runtime\n\nYour role is assigned; inherited lead conversation does not make you the lead. The brief and authoritative artifacts define your task. Do not invent a mission or frame when none is needed. The receiving contract is included below.\n\nCodex owns native agents, messaging, follow-ups, waiting and results. Locate the installed rubato-codex plugin's agent-taskforce skill in the available skill list for its Codex runtime adapter; resolve its links from that skill directory. Read the bundled dispatching skill before delegating. Do not start a substitute Rubato runtime or import Rubato provider aliases.\n\nRoles are not pinned to a model. For new helpers, choose an advertised GPT model and supported effort according to the bundled GPT allocation guide and the user's constraints. Keep existing owners for related follow-ups. Do not change your own assigned model or claim a runtime-confirmed model from a requested label.\n\nIf assigned a board task, preserve the lead's workspace and run_id. Your child thread ID must not replace that run_id. Use your actual native ID or canonical name as actor. The board records cooperative work state, not authentication or native liveness. Focused helpers stay board-free unless shared work is explicitly assigned.`;

await mkdir(path.join(root, 'agents'), { recursive: true });
for (const [name, description, source] of definitions) {
  const role = source
    ? body(await readFile(path.join(root, 'skills/agent-taskforce/teammate', source), 'utf8'))
    : '# Focused helper\n\nExecute the bounded task in your brief. Verify local facts and return evidence to the assigning owner. Implement only when authorized. You do not own the wider workstream or its integration. If it cannot be completed within your boundary or budget, return the covered surface, exact blocker and recommended next cut.';
  const instructions = [`# Taskforce role: ${name}`, runtime, role, receiving].join('\n\n');
  const digest = createHash('sha256').update(instructions).digest('hex');
  // Native role model fields override explicit spawn selection; omit both.
  const content = `${banner}\n# Source SHA256: ${digest}\nname = ${JSON.stringify(name)}\ndescription = ${JSON.stringify(description)}\ndeveloper_instructions = ${JSON.stringify(instructions)}\n`;
  const destination = path.join(root, 'agents', `${name}.toml`);
  if (check) {
    const installed = await readFile(destination, 'utf8');
    if (installed !== content) throw new Error(`Stale generated role: ${name}`);
  } else {
    await writeFile(destination, content);
  }
  process.stdout.write(`${name}: ${check ? 'current' : 'generated'}; model selected by lead\n`);
}
