#!/usr/bin/env node

import { createHash } from "node:crypto";
import { access, copyFile, cp, lstat, mkdir, readFile, readdir, realpath, rename, rm, writeFile } from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import { homedir } from "node:os";
import { basename, delimiter, dirname, isAbsolute, join, resolve, sep } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { discoverProviderCatalog, makeProviderPolicy, resolveProviderSelection } from "./providers.mjs";

const ROLE_NAMES = ["taskforce_owner", "taskforce_verifier", "taskforce_helper"];
const CONFIG_START = "# >>> rubato-codex managed bootstrap >>>";
const CONFIG_END = "# <<< rubato-codex managed bootstrap <<<";
const AGENTS_START = "<!-- >>> rubato-codex managed instructions >>> -->";
const AGENTS_END = "<!-- <<< rubato-codex managed instructions <<< -->";
const LEGACY_PREFIX = "# Generated by agent-taskforce/scripts/sync-codex-roles.mjs.";
const MIN_CODEX_VERSION = [0, 153, 4];

const ownDir = dirname(fileURLToPath(import.meta.url));
const defaultPluginRoot = resolve(ownDir, "..");
const defaultRepoRoot = resolve(defaultPluginRoot, "..");

function fail(message) {
  throw new Error(message);
}

function sha256(content) {
  return createHash("sha256").update(content).digest("hex");
}

function quoteToml(value) {
  return JSON.stringify(value);
}

async function exists(path) {
  try {
    await access(path, fsConstants.F_OK);
    return true;
  } catch {
    return false;
  }
}

async function readOptional(path) {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") return "";
    throw error;
  }
}

function replaceManagedBlock(content, start, end, block, { prepend = false } = {}) {
  const startAt = content.indexOf(start);
  const endAt = content.indexOf(end);
  if ((startAt === -1) !== (endAt === -1)) {
    fail(`incomplete managed block: ${start}`);
  }
  if (startAt !== -1) {
    if (content.indexOf(start, startAt + start.length) !== -1 || content.indexOf(end, endAt + end.length) !== -1) {
      fail(`duplicate managed block: ${start}`);
    }
    if (endAt < startAt) fail(`reversed managed block: ${start}`);
    const after = endAt + end.length;
    return `${content.slice(0, startAt)}${block}${content.slice(after)}`;
  }
  if (prepend) {
    const firstTable = content.search(/^\s*\[\[?[^\]\r\n]+\]\]?\s*(?:#.*)?$/m);
    if (firstTable === -1) {
      const preamble = content.length === 0 || content.endsWith("\n") ? content : `${content}\n`;
      return `${preamble}${preamble ? "\n" : ""}${block}\n`;
    }
    const preamble = content.slice(0, firstTable);
    const tables = content.slice(firstTable).replace(/^\n+/, "");
    const prefix = preamble.length === 0 || preamble.endsWith("\n") ? preamble : `${preamble}\n`;
    return `${prefix}${prefix && !prefix.endsWith("\n\n") ? "\n" : ""}${block}\n\n${tables}`;
  }
  const prefix = content.length === 0 || content.endsWith("\n") ? content : `${content}\n`;
  return `${prefix}${prefix.length === 0 ? "" : "\n"}${block}\n`;
}

function removeManagedBlock(content, start, end) {
  const startAt = content.indexOf(start);
  const endAt = content.indexOf(end);
  if (startAt === -1 && endAt === -1) return content;
  if (startAt === -1 || endAt < startAt) fail(`invalid managed block: ${start}`);
  let before = content.slice(0, startAt);
  let after = content.slice(endAt + end.length);
  if (before.endsWith("\n\n") && after.startsWith("\n")) after = after.slice(1);
  return `${before}${after}`.replace(/\n{3,}/g, "\n\n").replace(/^\n+|\n+$/g, "") + "\n";
}

function splitTomlSections(content) {
  const lines = content.split(/(?<=\n)/);
  const sections = [];
  let current = null;
  let offset = 0;
  for (const line of lines) {
    const match = line.match(/^\s*\[\[([^\]]+)\]\]\s*(?:#.*)?(?:\r?\n)?$/)
      || line.match(/^\s*\[([^\]]+)\]\s*(?:#.*)?(?:\r?\n)?$/);
    if (match) {
      if (current) current.end = offset;
      current = { name: match[1].trim(), start: offset, end: content.length };
      sections.push(current);
    }
    offset += line.length;
  }
  if (current) current.end = content.length;
  return sections;
}

function extractAndRemoveSections(content, matches) {
  const sections = splitTomlSections(content).filter((section) => matches(section.name, content.slice(section.start, section.end)));
  const extracted = sections.map((section) => content.slice(section.start, section.end).replace(/\s+$/g, ""));
  let stripped = content;
  for (const section of [...sections].sort((a, b) => b.start - a.start)) {
    stripped = stripped.slice(0, section.start) + stripped.slice(section.end);
  }
  return { stripped: stripped.replace(/\n{3,}/g, "\n\n"), extracted };
}

function extractAndRemoveRoleSections(content) {
  const wanted = new Set(ROLE_NAMES.map((name) => `agents.${name}`));
  return extractAndRemoveSections(content, (name) => wanted.has(name));
}

function extractAndRemoveMcpSections(content) {
  return extractAndRemoveSections(content, (name) => name === "mcp_servers.taskforce" || name.startsWith("mcp_servers.taskforce."));
}

function parseRoleDescription(content, name) {
  const match = content.match(/^description\s*=\s*("(?:[^"\\]|\\.)*")\s*$/m);
  if (!match) fail(`role ${name} has no quoted description`);
  return JSON.parse(match[1]);
}

function legacyStateDir(sections) {
  for (const section of sections) {
    if (!/^\s*TASKFORCE_STATE_DIR\s*=/m.test(section)) continue;
    const match = section.match(/^\s*TASKFORCE_STATE_DIR\s*=\s*("(?:[^"\\]|\\.)*"|'[^']*')\s*(?:#.*)?$/m);
    if (!match) fail("legacy taskforce MCP has an unsupported TASKFORCE_STATE_DIR value; refusing migration");
    return match[1].startsWith("\"") ? JSON.parse(match[1]) : match[1].slice(1, -1);
  }
  return null;
}

function assertSafeTomlEditing(content, path) {
  if (content.includes('"""') || content.includes("'''")) {
    fail(`refusing to edit ${path}: TOML multiline strings are not supported by the conservative section editor`);
  }
}

function makeConfigBlock(roleRecords, disabledSkillPaths) {
  const lines = [CONFIG_START];
  for (const role of roleRecords) {
    lines.push(
      `[agents.${role.name}]`,
      `description = ${quoteToml(role.description)}`,
      `config_file = ${quoteToml(role.target)}`,
      "",
    );
  }
  for (const path of disabledSkillPaths) {
    lines.push(
      "[[skills.config]]",
      `path = ${quoteToml(path)}`,
      "enabled = false",
      "",
    );
  }
  lines.push(CONFIG_END);
  return lines.join("\n");
}

function makeAgentsBlock(fragment) {
  return `${AGENTS_START}\n${fragment.trim()}\n${AGENTS_END}`;
}

function parseVersion(output) {
  const match = output.match(/(\d+)\.(\d+)\.(\d+)/);
  return match ? match.slice(1, 4).map(Number) : null;
}

function versionAtLeast(version, minimum) {
  for (let index = 0; index < minimum.length; index += 1) {
    if (version[index] > minimum[index]) return true;
    if (version[index] < minimum[index]) return false;
  }
  return true;
}

function executableFromPath(name) {
  for (const entry of (process.env.PATH || "").split(delimiter)) {
    if (entry) returnCandidates.push(join(entry, name));
  }
  return null;
}

const returnCandidates = [];

function probeCodex(path) {
  const versionResult = spawnSync(path, ["--version"], { encoding: "utf8" });
  if (versionResult.error || versionResult.status !== 0) return null;
  const versionText = `${versionResult.stdout}${versionResult.stderr}`.trim();
  const version = parseVersion(versionText);
  if (!version || !versionAtLeast(version, MIN_CODEX_VERSION)) return null;
  const pluginResult = spawnSync(path, ["plugin", "--help"], { encoding: "utf8" });
  if (pluginResult.error || pluginResult.status !== 0) return null;
  return { path, version: versionText };
}

function discoverCodex(explicitPath) {
  if (explicitPath) {
    const explicit = probeCodex(resolve(explicitPath));
    if (!explicit) fail(`--codex does not point to Codex >= ${MIN_CODEX_VERSION.join(".")} with plugin support: ${explicitPath}`);
    return explicit;
  }
  const candidates = [];
  if (process.env.CODEX_BINARY) candidates.push(process.env.CODEX_BINARY);
  if (process.platform === "darwin") candidates.push("/Applications/ChatGPT.app/Contents/Resources/codex");
  returnCandidates.length = 0;
  executableFromPath(process.platform === "win32" ? "codex.exe" : "codex");
  candidates.push(...returnCandidates);
  for (const candidate of [...new Set(candidates)]) {
    const result = probeCodex(candidate);
    if (result) return result;
  }
  fail(`could not find Codex >= ${MIN_CODEX_VERSION.join(".")} with native plugin support; pass --codex PATH`);
}

function runCodex(codex, args, codexHome, { mutate = false, dryRun = false } = {}) {
  if (dryRun && mutate) return { skipped: true, stdout: "" };
  const result = spawnSync(codex, args, {
    encoding: "utf8",
    env: { ...process.env, CODEX_HOME: codexHome },
  });
  if (result.error || result.status !== 0) {
    const detail = `${result.stderr || ""}${result.stdout || ""}`.trim();
    fail(`Codex command failed: ${codex} ${args.join(" ")}${detail ? `\n${detail}` : ""}`);
  }
  return result;
}

function parseJsonOutput(result, label) {
  try {
    return JSON.parse(result.stdout);
  } catch {
    fail(`${label} did not return JSON`);
  }
}

async function atomicWrite(path, content, mode) {
  await mkdir(dirname(path), { recursive: true });
  const temp = `${path}.rubato-codex-${process.pid}.tmp`;
  await writeFile(temp, content, mode ? { mode } : undefined);
  await rename(temp, path);
}

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

async function backupExisting(path, backupDir) {
  if (!(await exists(path))) return null;
  await mkdir(backupDir, { recursive: true });
  const backup = join(backupDir, basename(path));
  await copyFile(path, backup);
  return backup;
}

async function stageLocalMarketplace(pluginRoot, repoRoot, stageRoot) {
  const next = `${stageRoot}.next-${process.pid}`;
  await rm(next, { recursive: true, force: true });
  await mkdir(join(next, ".agents", "plugins"), { recursive: true });
  await mkdir(join(next, "rubato-codex", "taskforce", "dist"), { recursive: true });
  await copyFile(
    join(repoRoot, ".agents", "plugins", "marketplace.json"),
    join(next, ".agents", "plugins", "marketplace.json"),
  );
  await cp(join(pluginRoot, ".codex-plugin"), join(next, "rubato-codex", ".codex-plugin"), { recursive: true });
  await copyFile(join(pluginRoot, ".mcp.json"), join(next, "rubato-codex", ".mcp.json"));
  await cp(join(pluginRoot, "skills"), join(next, "rubato-codex", "skills"), { recursive: true });
  await mkdir(join(next, "rubato-codex", "scripts"), { recursive: true });
  await copyFile(
    join(pluginRoot, "scripts", "taskforce-mcp.sh"),
    join(next, "rubato-codex", "scripts", "taskforce-mcp.sh"),
  );
  await copyFile(
    join(pluginRoot, "taskforce", "dist", "mcp-server.mjs"),
    join(next, "rubato-codex", "taskforce", "dist", "mcp-server.mjs"),
  );
  const notices = join(pluginRoot, "taskforce", "THIRD_PARTY_NOTICES.md");
  if (await exists(notices)) {
    await copyFile(notices, join(next, "rubato-codex", "taskforce", "THIRD_PARTY_NOTICES.md"));
  }
  await rm(stageRoot, { recursive: true, force: true });
  await rename(next, stageRoot);
}

async function canonicalPath(path) {
  try {
    return await realpath(path);
  } catch {
    return resolve(path);
  }
}

async function sourceMatchesMarketplace(entry, source) {
  if (!entry) return false;
  const configured = entry.marketplaceSource?.source;
  if (configured === source) return true;
  if (isAbsolute(source) && entry.root && await canonicalPath(entry.root) === await canonicalPath(source)) return true;
  if (isAbsolute(source) && configured && await canonicalPath(configured) === await canonicalPath(source)) return true;
  return false;
}

async function loadPackage(pluginRoot, repoRoot) {
  const manifestPath = join(pluginRoot, ".codex-plugin", "plugin.json");
  const marketplacePath = join(repoRoot, ".agents", "plugins", "marketplace.json");
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  const marketplace = JSON.parse(await readFile(marketplacePath, "utf8"));
  if (!manifest.name || !marketplace.name) fail("plugin and marketplace must have names");
  const roleRecords = [];
  for (const name of ROLE_NAMES) {
    const source = join(pluginRoot, "agents", `${name}.toml`);
    const content = await readFile(source, "utf8");
    if (/^\s*(model|model_reasoning_effort)\s*=/m.test(content)) {
      fail(`role ${name} pins a model or reasoning effort`);
    }
    roleRecords.push({ name, source, content, description: parseRoleDescription(content, name) });
  }
  const instructions = await readFile(join(pluginRoot, "instructions", "AGENTS.md"), "utf8");
  const skillRecords = [];
  const skillEntries = await readdir(join(pluginRoot, "skills"), { withFileTypes: true });
  for (const name of skillEntries.filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort()) {
    const source = join(pluginRoot, "skills", name, "SKILL.md");
    skillRecords.push({ name, source, content: await readFile(source, "utf8") });
  }
  return { manifest, marketplace, roleRecords, instructions, skillRecords };
}

async function preflightRoleTargets(roleRecords, codexHome, previousState, legacyMigration) {
  const records = [];
  for (const role of roleRecords) {
    const target = join(codexHome, "agents", `${role.name}.toml`);
    const current = await readOptional(target);
    const previous = previousState?.roles?.[role.name];
    const sameAsPackage = current === role.content;
    const sameAsPreviousInstall = previous && current && sha256(current) === previous.installedSha;
    const legacy = current.startsWith(LEGACY_PREFIX);
    if (current && !sameAsPackage && !sameAsPreviousInstall && !(legacyMigration && legacy)) {
      fail(`role collision at ${target}; use --migrate-legacy only for generated legacy taskforce roles`);
    }
    records.push({ ...role, target, current, legacy, previous });
  }
  return records;
}

async function preflightLegacySkills(skillRecords, codexHome, previousState, legacyMigration, configContent, explicitSkillPaths = []) {
  const disabled = [...(previousState?.disabledSkillPaths || [])];
  const alreadyDisabled = new Set(disabled);
  const bundledNames = new Set(skillRecords.map((skill) => skill.name.toLowerCase()));
  const explicitRecords = [];
  for (const requestedPath of explicitSkillPaths) {
    const skillPath = resolve(requestedPath);
    if (basename(skillPath) !== "SKILL.md" || !bundledNames.has(basename(dirname(skillPath)).toLowerCase())) {
      fail(`--disable-skill must name a bundled skill's exact SKILL.md path: ${requestedPath}`);
    }
    if (!(await exists(skillPath))) fail(`--disable-skill path does not exist: ${skillPath}`);
    explicitRecords.push({ skillPath, canonical: await canonicalPath(skillPath) });
  }
  for (const skill of skillRecords) {
    const skillDir = join(codexHome, "skills", skill.name);
    if (!(await exists(skillDir))) continue;
    const skillPath = join(skillDir, "SKILL.md");
    if (alreadyDisabled.has(skillPath)) continue;
    const canonicalSkillPath = await canonicalPath(skillPath);
    const explicitlyAuthorized = explicitRecords.some((record) => record.canonical === canonicalSkillPath);
    if (!previousState && !legacyMigration && !explicitlyAuthorized) {
      fail(`legacy Codex skill collision at ${skillDir}; use --migrate-legacy to disable the recognized duplicate without moving it`);
    }
    let recognized = false;
    const info = await lstat(skillDir);
    if (info.isSymbolicLink()) {
      const resolved = await realpath(skillDir);
      recognized = basename(resolved).toLowerCase() === skill.name.toLowerCase()
        && resolved.includes(`${sep}.agents${sep}skills${sep}`);
    } else if (info.isDirectory()) {
      const currentSkill = await readOptional(join(skillDir, "SKILL.md"));
      recognized = currentSkill === skill.content;
    }
    recognized ||= explicitlyAuthorized;
    if (!recognized) fail(`refusing to disable unrecognized skill collision at ${skillDir}`);
    const existingConfig = splitTomlSections(configContent)
      .filter((section) => section.name === "skills.config")
      .map((section) => configContent.slice(section.start, section.end))
      .find((section) => section.includes(`path = ${quoteToml(skillPath)}`));
    if (existingConfig && !/^enabled\s*=\s*false\s*$/m.test(existingConfig)) {
      fail(`existing skills.config explicitly enables ${skillPath}; refusing to override it`);
    }
    if (!existingConfig) {
      disabled.push(skillPath);
      alreadyDisabled.add(skillPath);
    }
  }
  for (const { skillPath } of explicitRecords) {
    if (alreadyDisabled.has(skillPath)) continue;
    const existingConfig = splitTomlSections(configContent)
      .filter((section) => section.name === "skills.config")
      .map((section) => configContent.slice(section.start, section.end))
      .find((section) => section.includes(`path = ${quoteToml(skillPath)}`));
    if (existingConfig && !/^enabled\s*=\s*false\s*$/m.test(existingConfig)) {
      fail(`existing skills.config explicitly enables ${skillPath}; refusing to override it`);
    }
    if (!existingConfig) disabled.push(skillPath);
    alreadyDisabled.add(skillPath);
  }
  return disabled;
}

function ensureNodeVersion() {
  const major = Number(process.versions.node.split(".")[0]);
  if (major < 24) fail(`Node.js 24+ is required; found ${process.version}`);
}

export async function installPackage(options = {}) {
  ensureNodeVersion();
  const pluginRoot = resolve(options.pluginRoot || defaultPluginRoot);
  const repoRoot = resolve(options.repoRoot || defaultRepoRoot);
  const codexHome = resolve(options.codexHome || process.env.CODEX_HOME || join(homedir(), ".codex"));
  const codex = discoverCodex(options.codexPath);
  const dryRun = Boolean(options.dryRun);
  const stagedMarketplace = join(codexHome, "rubato-codex", "marketplace-source");
  const source = options.marketplaceSource || stagedMarketplace;
  const packageData = await loadPackage(pluginRoot, repoRoot);
  const marketplaceName = packageData.marketplace.name;
  const pluginName = packageData.manifest.name;
  const selector = `${pluginName}@${marketplaceName}`;
  const stateDir = join(codexHome, "rubato-codex");
  const statePath = join(stateDir, "install-state.json");
  const previousState = JSON.parse((await readOptional(statePath)) || "null");
  const providerPolicyPath = join(stateDir, "providers.json");
  const providerCatalog = await discoverProviderCatalog({ opencodexHome: options.opencodexHome });
  const providerSelection = await resolveProviderSelection({
    requested: options.providers,
    previous: previousState?.selectedProviders,
    catalog: providerCatalog,
    interactive: options.interactiveProviders ?? Boolean(process.stdin.isTTY && process.stdout.isTTY),
    prompt: options.providerPrompt,
  });
  const providerPolicy = makeProviderPolicy(providerCatalog, providerSelection.selected);
  const roles = await preflightRoleTargets(packageData.roleRecords, codexHome, previousState, options.legacyMigration);

  const configPath = join(codexHome, "config.toml");
  const agentsPath = join(codexHome, "AGENTS.md");
  const configOriginal = await readOptional(configPath);
  assertSafeTomlEditing(configOriginal, configPath);
  const configWithoutManaged = removeManagedBlock(configOriginal, CONFIG_START, CONFIG_END);
  const { stripped: configWithoutRoles, extracted: legacySections } = extractAndRemoveRoleSections(configWithoutManaged);
  const { stripped: configWithoutLegacyMcp, extracted: legacyMcpSections } = extractAndRemoveMcpSections(configWithoutRoles);
  if (legacySections.length && !options.legacyMigration && !previousState) {
    fail(`taskforce agent sections already exist in ${configPath}; rerun with --migrate-legacy only for generated legacy roles`);
  }
  if (legacySections.length && options.legacyMigration) {
    const legacyTargets = roles.filter((role) => role.current).every((role) => role.legacy);
    if (!legacyTargets) fail("refusing --migrate-legacy because existing role files are not generated legacy roles");
  }
  if (legacyMcpSections.length && !options.legacyMigration && !previousState) {
    fail(`legacy taskforce MCP sections already exist in ${configPath}; rerun with --migrate-legacy to replace the recognized installation`);
  }
  if (legacyMcpSections.length && options.legacyMigration) {
    const recognized = legacyMcpSections.some((section) => /mcp-server\.(?:js|mjs)/.test(section));
    if (!recognized) fail("refusing --migrate-legacy because the taskforce MCP section is not a recognized local installation");
    const previousStateDir = legacyStateDir(legacyMcpSections);
    const defaultStateDir = join(codexHome, "taskforce");
    if (previousStateDir && resolve(previousStateDir) !== resolve(defaultStateDir)) {
      fail(`legacy taskforce MCP uses custom TASKFORCE_STATE_DIR=${previousStateDir}; preserve that board explicitly before migrating (plugin default is ${defaultStateDir})`);
    }
  }
  const disabledSkillPaths = await preflightLegacySkills(
    packageData.skillRecords,
    codexHome,
    previousState,
    options.legacyMigration,
    configWithoutLegacyMcp,
    options.disableSkillPaths,
  );
  const roleConfigRecords = roles.map((role) => ({ name: role.name, description: role.description, target: role.target }));
  const configBase = previousState ? configWithoutManaged : configWithoutLegacyMcp;
  const configNext = replaceManagedBlock(
    configBase,
    CONFIG_START,
    CONFIG_END,
    makeConfigBlock(roleConfigRecords, disabledSkillPaths),
    { prepend: true },
  );
  const agentsOriginal = await readOptional(agentsPath);
  const agentsNext = replaceManagedBlock(agentsOriginal, AGENTS_START, AGENTS_END, makeAgentsBlock(packageData.instructions));

  if (!dryRun) await mkdir(codexHome, { recursive: true });

  const marketplacesResult = parseJsonOutput(
    runCodex(codex.path, ["plugin", "marketplace", "list", "--json"], codexHome),
    "plugin marketplace list",
  );
  const marketplace = (marketplacesResult.marketplaces || []).find((entry) => entry.name === marketplaceName);
  if (marketplace && !(await sourceMatchesMarketplace(marketplace, source))) {
    fail(`marketplace name collision: ${marketplaceName} points at ${marketplace.root || marketplace.marketplaceSource?.source || "another source"}`);
  }
  const pluginsResult = parseJsonOutput(
    runCodex(codex.path, ["plugin", "list", "--json"], codexHome),
    "plugin list",
  );
  const pluginInstalled = (pluginsResult.installed || []).some((entry) => entry.pluginId === selector || (entry.name === pluginName && entry.marketplaceName === marketplaceName));

  const plan = {
    action: "install",
    dryRun,
    codex: codex.path,
    codexVersion: codex.version,
    codexHome,
    marketplace: marketplace ? "already configured" : `add ${source}`,
    plugin: pluginInstalled ? `refresh ${selector}` : `add ${selector}`,
    roles: roles.map((role) => `${role.current ? "update" : "create"} ${role.target}`),
    disabledLegacySkills: disabledSkillPaths,
    legacyMcp: legacyMcpSections.length ? "replace recognized stanza" : "none",
    config: configPath,
    instructions: agentsPath,
    boardData: "preserved",
    providers: providerSelection.selected.length ? providerSelection.selected : ["native-codex-only"],
    providerSelection: providerSelection.source,
    providerPolicy: providerPolicyPath,
  };
  if (dryRun) return plan;

  const backupDir = join(stateDir, "backups", timestamp());
  const preservedState = previousState || {
    version: 1,
    legacyConfigSections: options.legacyMigration ? legacySections : [],
    legacyMcpSections: options.legacyMigration ? legacyMcpSections : [],
    disabledSkillPaths,
    configExisted: Boolean(configOriginal),
    agentsExisted: Boolean(agentsOriginal),
    roles: {},
  };
  preservedState.pluginSelector = selector;
  preservedState.marketplaceName = marketplaceName;
  preservedState.marketplaceAdded = previousState?.marketplaceAdded || !marketplace;
  preservedState.roles ||= {};
  preservedState.disabledSkillPaths = disabledSkillPaths;
  preservedState.selectedProviders = providerSelection.selected;
  if (!previousState) {
    preservedState.providerPolicy = {
      target: providerPolicyPath,
      previousExisted: await exists(providerPolicyPath),
      previousBackup: await backupExisting(providerPolicyPath, backupDir),
    };
  }
  preservedState.providerPolicy ||= { target: providerPolicyPath, previousExisted: false, previousBackup: null };
  preservedState.providerPolicy.installedSha = sha256(providerPolicy);

  if (!options.marketplaceSource) await stageLocalMarketplace(pluginRoot, repoRoot, stagedMarketplace);

  if (!marketplace) {
    const addArgs = ["plugin", "marketplace", "add", source];
    if (options.marketplaceRef) addArgs.push("--ref", options.marketplaceRef);
    if (options.marketplaceRef) addArgs.push("--sparse", ".agents/plugins", "--sparse", "rubato-codex");
    addArgs.push("--json");
    runCodex(codex.path, addArgs, codexHome, { mutate: true });
  }
  if (pluginInstalled) runCodex(codex.path, ["plugin", "remove", selector, "--json"], codexHome, { mutate: true });
  runCodex(codex.path, ["plugin", "add", selector, "--json"], codexHome, { mutate: true });

  await mkdir(join(codexHome, "agents"), { recursive: true });
  for (const role of roles) {
    let record = preservedState.roles[role.name];
    if (!record) {
      record = {
        target: role.target,
        previousExisted: Boolean(role.current),
        previousBackup: await backupExisting(role.target, backupDir),
      };
    }
    await atomicWrite(role.target, role.content, 0o600);
    record.installedSha = sha256(role.content);
    preservedState.roles[role.name] = record;
  }
  if (configOriginal && configOriginal !== configNext) await backupExisting(configPath, backupDir);
  if (agentsOriginal && agentsOriginal !== agentsNext) await backupExisting(agentsPath, backupDir);
  const configAfterPlugin = await readOptional(configPath);
  assertSafeTomlEditing(configAfterPlugin, configPath);
  const withoutManagedAfterPlugin = removeManagedBlock(configAfterPlugin, CONFIG_START, CONFIG_END);
  const withoutRolesAfterPlugin = extractAndRemoveRoleSections(withoutManagedAfterPlugin).stripped;
  const withoutMcpAfterPlugin = extractAndRemoveMcpSections(withoutRolesAfterPlugin).stripped;
  const finalConfig = replaceManagedBlock(
    withoutMcpAfterPlugin,
    CONFIG_START,
    CONFIG_END,
    makeConfigBlock(roleConfigRecords, disabledSkillPaths),
    { prepend: true },
  );
  await atomicWrite(configPath, finalConfig, 0o600);
  await atomicWrite(agentsPath, agentsNext, 0o600);
  await atomicWrite(providerPolicyPath, providerPolicy, 0o600);
  await atomicWrite(statePath, `${JSON.stringify(preservedState, null, 2)}\n`, 0o600);
  return plan;
}

export async function uninstallPackage(options = {}) {
  ensureNodeVersion();
  const codexHome = resolve(options.codexHome || process.env.CODEX_HOME || join(homedir(), ".codex"));
  const codex = discoverCodex(options.codexPath);
  const dryRun = Boolean(options.dryRun);
  const statePath = join(codexHome, "rubato-codex", "install-state.json");
  const stateText = await readOptional(statePath);
  if (!stateText) fail(`rubato-codex install state not found at ${statePath}`);
  const state = JSON.parse(stateText);
  const configPath = join(codexHome, "config.toml");
  const agentsPath = join(codexHome, "AGENTS.md");
  assertSafeTomlEditing(await readOptional(configPath), configPath);

  for (const [name, record] of Object.entries(state.roles || {})) {
    const current = await readOptional(record.target);
    if (current && sha256(current) !== record.installedSha) {
      fail(`refusing to overwrite modified installed role ${name}: ${record.target}`);
    }
  }
  if (state.providerPolicy?.installedSha) {
    const current = await readOptional(state.providerPolicy.target);
    if (current && sha256(current) !== state.providerPolicy.installedSha) {
      fail(`refusing to overwrite modified provider policy: ${state.providerPolicy.target}`);
    }
  }
  const pluginsResult = parseJsonOutput(
    runCodex(codex.path, ["plugin", "list", "--json"], codexHome),
    "plugin list",
  );
  const pluginInstalled = (pluginsResult.installed || []).some((entry) => entry.pluginId === state.pluginSelector);
  const plan = {
    action: "uninstall",
    dryRun,
    codex: codex.path,
    codexHome,
    plugin: pluginInstalled ? `remove ${state.pluginSelector}` : "already absent",
    marketplace: "preserved",
    roles: Object.keys(state.roles || {}),
    boardData: "preserved",
  };
  if (dryRun) return plan;
  if (pluginInstalled) runCodex(codex.path, ["plugin", "remove", state.pluginSelector, "--json"], codexHome, { mutate: true });

  let configNext = removeManagedBlock(await readOptional(configPath), CONFIG_START, CONFIG_END);
  const roleCollisions = extractAndRemoveRoleSections(configNext).extracted;
  const mcpCollisions = extractAndRemoveMcpSections(configNext).extracted;
  if (state.legacyConfigSections?.length || state.legacyMcpSections?.length) {
    if (roleCollisions.length || mcpCollisions.length) fail(`cannot restore legacy taskforce config because new taskforce sections exist in ${configPath}`);
    const trimmed = configNext.replace(/\s+$/g, "");
    const restored = [...(state.legacyConfigSections || []), ...(state.legacyMcpSections || [])];
    configNext = `${trimmed}${trimmed ? "\n\n" : ""}${restored.join("\n\n")}\n`;
  }
  const agentsNext = removeManagedBlock(await readOptional(agentsPath), AGENTS_START, AGENTS_END);
  if (!state.configExisted && !configNext.trim()) await rm(configPath, { force: true });
  else await atomicWrite(configPath, configNext, 0o600);
  if (!state.agentsExisted && !agentsNext.trim()) await rm(agentsPath, { force: true });
  else await atomicWrite(agentsPath, agentsNext, 0o600);

  for (const record of Object.values(state.roles || {})) {
    if (record.previousExisted && record.previousBackup) {
      await copyFile(record.previousBackup, record.target);
    } else {
      await rm(record.target, { force: true });
    }
  }
  if (state.providerPolicy?.previousExisted && state.providerPolicy.previousBackup) {
    await copyFile(state.providerPolicy.previousBackup, state.providerPolicy.target);
  } else {
    await rm(state.providerPolicy?.target || join(codexHome, "rubato-codex", "providers.json"), { force: true });
  }
  await rm(statePath, { force: true });
  return plan;
}

function usage() {
  return `Usage: ./install.sh [install|uninstall|plan] [options]\n\nOptions:\n  --codex PATH               use this Codex binary\n  --codex-home DIR           isolate or select Codex home\n  --marketplace-source SRC   local path or Git marketplace source\n  --marketplace-ref REF      Git ref; adds sparse repo paths\n  --migrate-legacy           back up and replace generated legacy taskforce roles\n  --providers LIST           OpenCodex provider IDs, comma-separated; 'none' means native only\n  --disable-skill PATH       disable an exact duplicate global SKILL.md; repeatable\n  --dry-run                  print the plan without changing files or plugin state\n`;
}

function parseArgs(argv) {
  const args = [...argv];
  let command = "install";
  if (args[0] && ["install", "uninstall", "plan"].includes(args[0])) command = args.shift();
  const options = { dryRun: command === "plan", legacyMigration: false };
  while (args.length) {
    const flag = args.shift();
    if (flag === "--dry-run") options.dryRun = true;
    else if (flag === "--migrate-legacy") options.legacyMigration = true;
    else if (flag === "--codex") options.codexPath = args.shift() || fail("--codex needs a path");
    else if (flag === "--codex-home") options.codexHome = args.shift() || fail("--codex-home needs a directory");
    else if (flag === "--marketplace-source") options.marketplaceSource = args.shift() || fail("--marketplace-source needs a value");
    else if (flag === "--marketplace-ref") options.marketplaceRef = args.shift() || fail("--marketplace-ref needs a value");
    else if (flag === "--providers") options.providers = args.shift() || fail("--providers needs a value");
    else if (flag === "--disable-skill") (options.disableSkillPaths ||= []).push(args.shift() || fail("--disable-skill needs a path"));
    else if (flag === "--help" || flag === "-h") return { help: true };
    else fail(`unknown argument: ${flag}`);
  }
  return { command, options };
}

async function main() {
  const parsed = parseArgs(process.argv.slice(2));
  if (parsed.help) {
    process.stdout.write(usage());
    return;
  }
  const result = parsed.command === "uninstall"
    ? await uninstallPackage(parsed.options)
    : await installPackage(parsed.options);
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    process.stderr.write(`rubato-codex: ${error.message}\n`);
    process.exitCode = 1;
  });
}
