import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const GENERATED_BANNER = "// Generated by ";

export function hasGeneratedShimBanner(content) {
  return String(content ?? "").startsWith(GENERATED_BANNER);
}

function isInsideExtensionsDirectory(path, agentDir) {
  return resolve(dirname(path)) === resolve(agentDir, "extensions");
}

function isGeneratedShim(path) {
  try {
    return hasGeneratedShimBanner(readFileSync(path, "utf8"));
  } catch {
    return false;
  }
}

/** Generated shims are ignored; bannerless writes count as reloads. */
export function excludeGeneratedExtensionShims(paths, agentDir) {
  return paths.filter((path) => !(isInsideExtensionsDirectory(path, agentDir) && isGeneratedShim(path)));
}
