// Settings > 기억. The page, its route and its server route are ours; the edits
// below only register them: a nav entry, a device-only page (no scope picker),
// the route in the generated tree, and the HTTP route on the server.
export const memoryOverlays = [
  'apps/server/src/RubatoMemory.ts',
  'apps/web/src/state/rubatoMemory.ts',
  'apps/web/src/components/settings/RubatoMemorySettings.tsx',
  'apps/web/src/routes/settings.memory.tsx',
];

export const memoryEdits = {
  'apps/server/src/server.ts': [
    ['import { deviceHubProxyRouteLayer } from "./device/DeviceHubProxy.ts";', 'import { rubatoMemoryRouteLayer } from "./RubatoMemory.ts";\n'],
    ['    deviceHubProxyRouteLayer,\n', '    rubatoMemoryRouteLayer,\n'],
  ],
  'apps/web/src/components/settings/settingsSearch.ts': [
    ['  | "/settings/storage"\n', '  | "/settings/memory"\n'],
    ['  "/settings/providers": "Providers",\n', '  "/settings/providers": "Providers",\n  "/settings/memory": "기억",\n', 'replace'],
    ['  "/settings/storage": "project-defaults",\n', '  "/settings/memory": null,\n'],
  ],
  'apps/web/src/components/settings/SettingsSidebarNav.tsx': [
    ['  BotIcon,\n', '  BotIcon,\n  BrainIcon,\n', 'replace'],
    ['  "/settings/storage": HardDriveIcon,\n', '  "/settings/memory": BrainIcon,\n'],
  ],
  'apps/web/src/routes/settings.tsx': [
    ['  "/settings/connections",\n]);', '  "/settings/connections",\n  "/settings/memory",\n]);', 'replace'],
  ],
  // The router plugin writes this file from routes/ at dev and build time; these
  // are exactly its lines for settings.memory.tsx, so a rebuild leaves it as is.
  // Three blocks share the same neighbours, so those anchors start at their header.
  'apps/web/src/routeTree.gen.ts': [
    ["import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'\n", "import { Route as SettingsMemoryRouteImport } from './routes/settings.memory'\n"],
    ["const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({\n", "const SettingsMemoryRoute = SettingsMemoryRouteImport.update({\n  id: '/memory',\n  path: '/memory',\n  getParentRoute: () => SettingsRoute,\n} as any)\n"],
    ["export interface FileRoutesByFullPath {\n  '/': typeof ChatIndexRoute\n  '/connect': typeof ConnectRoute\n  '/pair': typeof PairRoute\n  '/settings': typeof SettingsRouteWithChildren\n  '/usage': typeof UsageRoute\n  '/welcome': typeof WelcomeRoute\n  '/pull-requests': typeof ChatPullRequestsRoute\n  '/projects/$projectKey': typeof ProjectsProjectKeyRoute\n  '/settings/appearance': typeof SettingsAppearanceRoute\n  '/settings/archived': typeof SettingsArchivedRoute\n  '/settings/connections': typeof SettingsConnectionsRoute\n  '/settings/diagnostics': typeof SettingsDiagnosticsRoute\n  '/settings/general': typeof SettingsGeneralRoute\n  '/settings/integrations': typeof SettingsIntegrationsRoute\n  '/settings/keybindings': typeof SettingsKeybindingsRoute\n", "export interface FileRoutesByFullPath {\n  '/': typeof ChatIndexRoute\n  '/connect': typeof ConnectRoute\n  '/pair': typeof PairRoute\n  '/settings': typeof SettingsRouteWithChildren\n  '/usage': typeof UsageRoute\n  '/welcome': typeof WelcomeRoute\n  '/pull-requests': typeof ChatPullRequestsRoute\n  '/projects/$projectKey': typeof ProjectsProjectKeyRoute\n  '/settings/appearance': typeof SettingsAppearanceRoute\n  '/settings/archived': typeof SettingsArchivedRoute\n  '/settings/connections': typeof SettingsConnectionsRoute\n  '/settings/diagnostics': typeof SettingsDiagnosticsRoute\n  '/settings/general': typeof SettingsGeneralRoute\n  '/settings/integrations': typeof SettingsIntegrationsRoute\n  '/settings/keybindings': typeof SettingsKeybindingsRoute\n  '/settings/memory': typeof SettingsMemoryRoute\n", "replace"],
    ["export interface FileRoutesByTo {\n  '/connect': typeof ConnectRoute\n  '/pair': typeof PairRoute\n  '/settings': typeof SettingsRouteWithChildren\n  '/usage': typeof UsageRoute\n  '/welcome': typeof WelcomeRoute\n  '/pull-requests': typeof ChatPullRequestsRoute\n  '/projects/$projectKey': typeof ProjectsProjectKeyRoute\n  '/settings/appearance': typeof SettingsAppearanceRoute\n  '/settings/archived': typeof SettingsArchivedRoute\n  '/settings/connections': typeof SettingsConnectionsRoute\n  '/settings/diagnostics': typeof SettingsDiagnosticsRoute\n  '/settings/general': typeof SettingsGeneralRoute\n  '/settings/integrations': typeof SettingsIntegrationsRoute\n  '/settings/keybindings': typeof SettingsKeybindingsRoute\n", "export interface FileRoutesByTo {\n  '/connect': typeof ConnectRoute\n  '/pair': typeof PairRoute\n  '/settings': typeof SettingsRouteWithChildren\n  '/usage': typeof UsageRoute\n  '/welcome': typeof WelcomeRoute\n  '/pull-requests': typeof ChatPullRequestsRoute\n  '/projects/$projectKey': typeof ProjectsProjectKeyRoute\n  '/settings/appearance': typeof SettingsAppearanceRoute\n  '/settings/archived': typeof SettingsArchivedRoute\n  '/settings/connections': typeof SettingsConnectionsRoute\n  '/settings/diagnostics': typeof SettingsDiagnosticsRoute\n  '/settings/general': typeof SettingsGeneralRoute\n  '/settings/integrations': typeof SettingsIntegrationsRoute\n  '/settings/keybindings': typeof SettingsKeybindingsRoute\n  '/settings/memory': typeof SettingsMemoryRoute\n", "replace"],
    ["export interface FileRoutesById {\n  __root__: typeof rootRouteImport\n  '/_chat': typeof ChatRouteWithChildren\n  '/connect': typeof ConnectRoute\n  '/pair': typeof PairRoute\n  '/settings': typeof SettingsRouteWithChildren\n  '/usage': typeof UsageRoute\n  '/welcome': typeof WelcomeRoute\n  '/_chat/pull-requests': typeof ChatPullRequestsRoute\n  '/projects/$projectKey': typeof ProjectsProjectKeyRoute\n  '/settings/appearance': typeof SettingsAppearanceRoute\n  '/settings/archived': typeof SettingsArchivedRoute\n  '/settings/connections': typeof SettingsConnectionsRoute\n  '/settings/diagnostics': typeof SettingsDiagnosticsRoute\n  '/settings/general': typeof SettingsGeneralRoute\n  '/settings/integrations': typeof SettingsIntegrationsRoute\n  '/settings/keybindings': typeof SettingsKeybindingsRoute\n", "export interface FileRoutesById {\n  __root__: typeof rootRouteImport\n  '/_chat': typeof ChatRouteWithChildren\n  '/connect': typeof ConnectRoute\n  '/pair': typeof PairRoute\n  '/settings': typeof SettingsRouteWithChildren\n  '/usage': typeof UsageRoute\n  '/welcome': typeof WelcomeRoute\n  '/_chat/pull-requests': typeof ChatPullRequestsRoute\n  '/projects/$projectKey': typeof ProjectsProjectKeyRoute\n  '/settings/appearance': typeof SettingsAppearanceRoute\n  '/settings/archived': typeof SettingsArchivedRoute\n  '/settings/connections': typeof SettingsConnectionsRoute\n  '/settings/diagnostics': typeof SettingsDiagnosticsRoute\n  '/settings/general': typeof SettingsGeneralRoute\n  '/settings/integrations': typeof SettingsIntegrationsRoute\n  '/settings/keybindings': typeof SettingsKeybindingsRoute\n  '/settings/memory': typeof SettingsMemoryRoute\n", "replace"],
    ["  fullPaths:\n    | '/'\n    | '/connect'\n    | '/pair'\n    | '/settings'\n    | '/usage'\n    | '/welcome'\n    | '/pull-requests'\n    | '/projects/$projectKey'\n    | '/settings/appearance'\n    | '/settings/archived'\n    | '/settings/connections'\n    | '/settings/diagnostics'\n    | '/settings/general'\n    | '/settings/integrations'\n    | '/settings/keybindings'\n", "  fullPaths:\n    | '/'\n    | '/connect'\n    | '/pair'\n    | '/settings'\n    | '/usage'\n    | '/welcome'\n    | '/pull-requests'\n    | '/projects/$projectKey'\n    | '/settings/appearance'\n    | '/settings/archived'\n    | '/settings/connections'\n    | '/settings/diagnostics'\n    | '/settings/general'\n    | '/settings/integrations'\n    | '/settings/keybindings'\n    | '/settings/memory'\n", "replace"],
    ["  to:\n    | '/connect'\n    | '/pair'\n    | '/settings'\n    | '/usage'\n    | '/welcome'\n    | '/pull-requests'\n    | '/projects/$projectKey'\n    | '/settings/appearance'\n    | '/settings/archived'\n    | '/settings/connections'\n    | '/settings/diagnostics'\n    | '/settings/general'\n    | '/settings/integrations'\n    | '/settings/keybindings'\n", "  to:\n    | '/connect'\n    | '/pair'\n    | '/settings'\n    | '/usage'\n    | '/welcome'\n    | '/pull-requests'\n    | '/projects/$projectKey'\n    | '/settings/appearance'\n    | '/settings/archived'\n    | '/settings/connections'\n    | '/settings/diagnostics'\n    | '/settings/general'\n    | '/settings/integrations'\n    | '/settings/keybindings'\n    | '/settings/memory'\n", "replace"],
    ["  id:\n    | '__root__'\n    | '/_chat'\n    | '/connect'\n    | '/pair'\n    | '/settings'\n    | '/usage'\n    | '/welcome'\n    | '/_chat/pull-requests'\n    | '/projects/$projectKey'\n    | '/settings/appearance'\n    | '/settings/archived'\n    | '/settings/connections'\n    | '/settings/diagnostics'\n    | '/settings/general'\n    | '/settings/integrations'\n    | '/settings/keybindings'\n", "  id:\n    | '__root__'\n    | '/_chat'\n    | '/connect'\n    | '/pair'\n    | '/settings'\n    | '/usage'\n    | '/welcome'\n    | '/_chat/pull-requests'\n    | '/projects/$projectKey'\n    | '/settings/appearance'\n    | '/settings/archived'\n    | '/settings/connections'\n    | '/settings/diagnostics'\n    | '/settings/general'\n    | '/settings/integrations'\n    | '/settings/keybindings'\n    | '/settings/memory'\n", "replace"],
    ["    '/settings/keybindings': {\n      id: '/settings/keybindings'\n", "    '/settings/memory': {\n      id: '/settings/memory'\n      path: '/memory'\n      fullPath: '/settings/memory'\n      preLoaderRoute: typeof SettingsMemoryRouteImport\n      parentRoute: typeof SettingsRoute\n    }\n"],
    ["  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute\n", "  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute\n  SettingsMemoryRoute: typeof SettingsMemoryRoute\n", "replace"],
    ["  SettingsKeybindingsRoute: SettingsKeybindingsRoute,\n", "  SettingsKeybindingsRoute: SettingsKeybindingsRoute,\n  SettingsMemoryRoute: SettingsMemoryRoute,\n", "replace"],
  ],
};
