import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import {
  agentExtensionShim,
  ensureAgentExtensions,
  OWNED_AGENT_EXTENSIONS,
  RUBATO_EXTENSION_BANNER,
} from "../../src/agent-extensions.mjs";

test("the owned tps shim points at our module and never carries senpi's banner", () => {
  const agentDir = mkdtempSync(join(tmpdir(), "rubato-ext-"));
  const written = ensureAgentExtensions(agentDir);
  const target = join(agentDir, "extensions", "tps.js");
  assert.deepEqual(written, [target]);
  const content = readFileSync(target, "utf8");
  assert.ok(content.startsWith(RUBATO_EXTENSION_BANNER));
  assert.doesNotMatch(content, /^\/\/ Generated by/);
  assert.ok(content.includes(pathToFileURL(OWNED_AGENT_EXTENSIONS["tps.js"]).href));
  assert.deepEqual(ensureAgentExtensions(agentDir), []);
});

test("a senpi-generated shim in the way is replaced by ours", () => {
  const agentDir = mkdtempSync(join(tmpdir(), "rubato-ext-"));
  mkdirSync(join(agentDir, "extensions"), { recursive: true });
  const target = join(agentDir, "extensions", "tps.js");
  writeFileSync(target, "// Generated by senpi. Delete this file to stop loading the default global extension.\nexport { default } from \"file:///nowhere.js\";\n");
  ensureAgentExtensions(agentDir);
  assert.equal(readFileSync(target, "utf8"), agentExtensionShim(OWNED_AGENT_EXTENSIONS["tps.js"]));
});
