export const JAVASCRIPT_KERNEL_PRELUDE = [
	"print(...values): write stdout text.",
	"display(value): emit JSON, image, or markdown display output.",
	"log(message): emit a progress log line.",
	"phase(title): emit a progress phase.",
	"env(key?, value?): read, set, or list environment values.",
	"read(path, options?): read UTF-8 text; plain paths use cwd and local:// uses the session local root.",
	"write(path, content): write UTF-8 or binary data and return the resolved path.",
	"tool.<name>(args): request a host tool call through the bridge.",
	"completion(prompt, options?): request a host completion bridge call.",
	"output(...ids, options?): retrieve task output through the reserved output bridge.",
	"agent(prompt, options?): delegate work through the reserved agent bridge.",
	"parallel(thunks): run async thunks through the configured bounded pool; preserves order and rethrows the lowest-index error after all settle.",
	"pipeline(items, ...stages): map items through staged async transforms with a barrier between stages.",
].join("\n");
